name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Brew dependencies
      run: brew bundle

    - name: Install Global Yarn dependencies
      run: yarn install

    - name: Install Functions Yarn dependencies
      run: yarn install
      working-directory: ${{env.working-directory}}

    - name: Deploy
      run: yarn firebase deploy --token ${{ secrets.GCLOUD_TOKEN }}